### PR TITLE
Making delaunay-triangulator available via maven

### PR DESCRIPTION
**Pull request by phaus**
Since I plan to play around with this awesome library, I update the build configuration to have the library deployed to maven.

I am currently using my own Maven Repo, but since this is public available, it might be a good starting point.

You just have to add it to your project:

```xml
…
  <repository>
    <id>maven.javastream.de</id>
    <name>javastream Repository</name>
    <url>http://maven.javastream.de</url>
    <snapshots>
	<enabled>true</enabled>
    </snapshots>
  </repository>
…
```

After that you can add _delaunay-triangulator_ as a normal dependency:

```xml
…
  <dependencies>
    …
    <dependency>
      <groupId>io.github.jdiemke</groupId>
      <artifactId>delaunay-triangulation</artifactId>
      <version>1.0.3</version>
    </dependency>
    …
  </dependencies>
…
```

Fixing #3

### CODE REVIEW

**Comment by jdiemke** [comment]
Thanks a lot!

**Comment by LeWimbes** [comment]
Hi,
can I still access this project through your nexus, @phaus ? And if yes, how can I do so?
Thank you :)

**Comment by phaus** [comment]
@LeWimbes yes. I had to fix a build. It should be there now. You can also use https://maven.javastream.de as the repository server, if you want.

**Comment by LeWimbes** [comment]
Thanks

**Pull request merged**
